// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhs7bHPuLZVBw18M3R8b2MiNNfGeMUU-s',
    appId: '1:219493331473:web:ce84217e27bff637da77b0',
    messagingSenderId: '219493331473',
    projectId: 'quiz-app-9e97a',
    authDomain: 'quiz-app-9e97a.firebaseapp.com',
    storageBucket: 'quiz-app-9e97a.appspot.com',
    measurementId: 'G-2S53JJHKJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGtR-JY8wTIq1DilsAU_35AY9UgfRmxw',
    appId: '1:219493331473:android:7536121330348817da77b0',
    messagingSenderId: '219493331473',
    projectId: 'quiz-app-9e97a',
    storageBucket: 'quiz-app-9e97a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNsq2NBJDkiO2GB05bVtyYUerC6xQXBKQ',
    appId: '1:219493331473:ios:d5addbb937e8d0feda77b0',
    messagingSenderId: '219493331473',
    projectId: 'quiz-app-9e97a',
    storageBucket: 'quiz-app-9e97a.appspot.com',
    iosClientId: '219493331473-3ghnhgkegaj8dl9n0jhmuccc7fir3apo.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNsq2NBJDkiO2GB05bVtyYUerC6xQXBKQ',
    appId: '1:219493331473:ios:e5ebebd96e5769dfda77b0',
    messagingSenderId: '219493331473',
    projectId: 'quiz-app-9e97a',
    storageBucket: 'quiz-app-9e97a.appspot.com',
    iosClientId: '219493331473-g98leje62fug7up4jtdv1mo7lm40b2o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
